#!/usr/bin/perl

my $device = `qdbus org.kde.kmix | grep "output" | grep "analog"`;
   $device =~ s/\n//g;

my $qdbus=`qdbus org.kde.kmix $device org.kde.KMix.Control.volume`;
   $qdbus =~ s/\n//g;

print "$qdbus%\n";
