#!/usr/bin/perl

use 5.010;

# Capture errors as normal output
open STDERR, '>&STDOUT';

# Devices to Monitor
my $eth_device   = "lan";
my $wifi_device  = "wifi";
my $usb_device   = "jmac-usbwifi";
my $sleepytime   = "14"; # Force pause!
my @devices      = ( $eth_device, $usb_device, $wifi_device );

# Used to list/discover ap's
my $open = 0;
my $closed = 0;

# Main Program
# Grab first active device
# -> wired, then usb, then wifi checked - first one active is grabbed.
my $active_device = determine_active_device();

# Detect device status
#  only print the following output if ethernet and usb are inactive (wifi is left)
if ( $active_device ne ( $eth_device || $usb_device ) ) {

    # Detect Wifi rfkill status
    if ( get_rfkill_status() eq "yes" ) {
        print "WiFi Disabled\n";
        sleep 2;
        exit;
    }

    if ( ! $active_device ) {
        # No ip address, so lets just count wifinetworks available
        print "<html>Networks \(" . &FindAPs( $wifi_device) . "\)</html>\n";
        sleep 2;
        exit;
    }
   
    # Wifi looks connected so far, so lets slurp data!
    my ( $active_ip, $active_bcast, $active_mask ) = get_ip_info ( $active_device );
    my ( $essid, $rate, $apmac, $encryption, $security_mode, $power_management, $mode, $frequency, $quality, $signal, $noise ) = get_wifi_info ( $active_device );
    my ( $latency, $output );

    # Slow/Bad Wifi connection
    if ( $rate == ( 1 or 5 ) ) {
        print "<html>\"$essid\" \@ $rate Mb\/s \(<font\ color=\"red\">NEED RECONNECT<\/font>\)</html>\n";
        sleep $sleepytime;
        exit;
    } else {
        $latency = get_latency();
    }

    $output = "<html>";

    if ( $encryption ) {
        $output .= "<b><font\ color=\"green\">Safe</font></b>";
    } else {
        $output .= "<b>Public</b>";
    }

    $output .= " \"$essid\" \@ $rate Mb\/s ";
    $output .= format_latency( $latency );
    $output .= "</html>";

    print $output;


} elsif ( $active_device ne $wifi_device ) {
    # Looks like we have a wired connection
    
    my ( $active_ip, $active_bcast, $active_mask ) = get_ip_info ( $active_device );
    my $latency = get_latency();

    print "<html>Physical <b>\($active_device\)</b> $active_ip " . &format_latency( $latency ) . "</html>\n";

} else {
    # Something is wrong
    print "something is wrong\n";
}


sleep $sleepytime;
exit;

# Loop through devices, if it's got an ip it's up (hopefully)
sub determine_active_device {

    foreach my $device ( @devices )  {
    my $ifconfig = `ifconfig $device 2>/dev/null`;
        if ($ifconfig =~/inet addr:(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/gi) {
            return $device;
            last;
        }
    }
}

sub get_rfkill_status {
    my $rfkill_cmd = `rfkill list wifi | head -3 | grep "Hard"`; 
    $rfkill_cmd =~ /.*Hard\ blocked: (.*)/; 
    my $killed = $1;
  return $killed;
}


# Get ip data
sub get_ip_info {

    my ( $ip, $bcast, $mask );
    my $ifconfigdata = `ifconfig $1`;

    if ($ifconfigdata =~/inet addr:(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/gi) {
        $ip = $1;
    } else {
        $ip = '<no IP-Address>';
    }
    if ($ifconfigdata =~/Bcast:(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/gi) {
        $bcast = $1;
    }
    if ($ifconfigdata =~/Mask:(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/gi) {
        $mask = $1;
    }

  return ( $ip, $bcast, $mask );
}

# Get Wifi Specific Stuff
sub get_wifi_info {

    my ( $essid, $rate, $apmac, $encryption, $security_mode, $power_management, $mode, $frequency, $quality, $signal, $noise );
    my $iwconfigdata = `sudo iwconfig $1 2>/dev/null`;

    # If we are wired, forget it.
    if ($iwconfigdata =~/no\ wireless\ extensions./gi) {

      return ( "wired" );

    } else {

        if ($iwconfigdata =~/ESSID:\"(.*)\"/gi) {
            $essid = $1;
        }
        if ($iwconfigdata =~/Bit\ Rate\=(.*)\ Mb/gi) {
            $rate = $1;
        }
        if ($iwconfigdata =~/Access Point:\s+(\w\w:\w\w:\w\w:\w\w:\w\w:\w\w)/gi) {
            $apmac = $1;
        }
        if ($iwconfigdata =~/Encryption key:(.*?)\s/gi) {
            $encryption = $1;
        }
        if ($iwconfigdata =~/Security mode:(.*?)\s/gi) {
            $security_mode = $1;
        }
        if ($iwconfigdata =~/Power Management( period)?:(.*?)\s/gi) {
            $power_management = $2;
        }

        if ($iwconfigdata =~/Mode:\s*(Managed|Ad\-hoc|Auto|Master)\s*/i) {
            $mode = $1;
        }
        if ($iwconfigdata =~/Frequency:\s*([\w\.]+)\s*/i) {
            $frequency = $1;
        }
        if ($iwconfigdata =~/Quality:(.*?)\s/i) {
            $quality = $1;
        }
        if (iwconfigdata =~/Signal level:(.*?)\sdBm/i) {
            $signal = $1;
        }
        if (iwconfigdata =~/Noise level:(.*?)\s*dBm/i) {
            $noise = $1;
        }

      return ( $essid, $rate, $apmac, $encryption, $security_mode, $power_management, $mode, $frequency, $quality, $signal, $noise ); 
    }

}

# Do latency test, can do better - fix later
sub get_latency {

    my $cmd = "httping -c 7 -i 3 -m www.google.com";    
    my @output = `$cmd`;
    chomp @output;

    my $total = ($output[1] + $output[2] + $output[3] + $output[4] + $output[5] + $output[6] + $output[7]) / 7;
    $rounded = sprintf( "%.0f", $total );
  return $rounded;

}

# Present nice html color codes
sub format_latency {
    my $latency = shift;
    my $string;

    given ( $latency ) {
        # Handle Odd Stuff
        when ( -1 )         { $string = "\(<font\ color=\"white\">ERROR on $essid<\/font>\)";
                                if ( $essid eq "Tullys Free WiFi" ) {
                                    `sudo /etc/wicd/scripts/postconnect/tullyslogin`;
                                }
                            }
        when ( 0 )          { $string = "\(<font\ color=\"white\">NO CONNECTION<\/font>\)"; }

        # Handle Color Coded Latency 

        when ( $_ < 100  )   { $string = "\($latency ms\)"; }
        when ( $_ < 400  )   { $string = "\(<font\ color=\"green\">$latency ms<\/font>\)" }
        when ( $_ < 700  )   { $string = "\(<font\ color=\"blue\">$latency ms<\/font>\)" }
        when ( $_ < 1000 )   { $string = "\(<font\ color=\"yellow\">$latency ms<\/font>\)" }
        when ( $_ < 1500 )   { $string = "\(<font\ color=\"orange\">$latency ms<\/font>\)" }

        # Fallthrough, red text
        default             { $string = " \(<font\ color=\"red\">$latency ms<\/font>\)"; }
    }

  return $string;
}

## find access points for unconnected wifi counts
sub FindAPs {
    my $apoints = `sudo /sbin/iwlist $1 scanning 2> /dev/null`;
    my @spoints = split /Cell/, $apoints;

    my $j=0;
    undef(@Address);
    undef(@Encryption);

    ## parse found APs
    for (my $i=0; $i<=$#spoints; $i++) {

        if ($spoints[$i] =~/Address:\s*(\w\w:\w\w:\w\w:\w\w:\w\w:\w\w)/i) {
            $j++;
            $Address[$j] = $1;

            if ($spoints[$i] =~/Encryption key:\s*(on|off)\s*/i) {
                $Encryption[$j] = $1;
            }
        }
    }

    ## show found APs
    &ListOpenAPs;
    &ListClosedAPs;
    my $string;
    if ( $open ne "0" ) {
        $string = "<b> $open Open</b> / $closed Encrypted ";
    } else {
        $string = "$closed Encrypted";
    }
  return $string;
}


## list APs
sub ListClosedAPs {
    for (my $j=1; $j<=$#Address; $j++) {
	next if ( $Encryption[$j] ne "on" );
        $closed++;
    }
}


## list APs
sub ListOpenAPs {
    for (my $j=1; $j<=$#Address; $j++) {
	next if ( $Encryption[$j] eq "on" );
        $open++;
    }
}
