#!/bin/bash
. ~/.Xdbus

# Rsync Options (and descriptions)
# -r                    Recurse Dirs
# -t                    Preserve Timestamps
# -s                    Protect Args (pass spaces, special chars to remote)
# --delete              Nuke extra files in destination
# -m                    Prune empty dirs

rsync -r -t -v -m --delete --progress --exclude *.pdf --exclude The\ Kindle\ Archive/* -s /home/cmauch/Documents/Book\ Collection/ /home/cmauch/Dropbox/Book\ Collection/
rsync -r -t -v -m --delete --progress --exclude *.pdf --exclude The\ Kindle\ Archive/* -s /home/cmauch/Documents/Book\ Collection/ /home/cmauch/Insync/cmauch\@gmail.com/Book\ Collection/


