#!/bin/bash
. ~/.Xdbus

# Rsync Options (and descriptions)
# -r                    Recurse Dirs
# -t                    Preserve Timestamps
# --modify-window=1     Timestamps can be off by 1 second (MS Windows Compat)
# -s                    Protect Args (pass spaces, special chars to remote)
ROPTION="-r -t -v --progress --modify-window=1 -s"
RAWK="awk -f /home/cmauch/dotfiles/rsync.awk"
RZEN="zenity --progress --title \"Backup\"  --text=\"Scanning...\" --percentage=0 --auto-kill --auto-close"
EXCLUDES="/home/cmauch/dotfiles/rsync"

if [ -n "/run/media/cmauch/BigWindows" ]; then

# Music
rsync $ROPTION --delete /home/cmauch/Music/Organized\ Music /run/media/cmauch/BigWindows/ 
rsync $ROPTION --delete /home/cmauch/Music/Collections /run/media/cmauch/BigWindows/ 

# Pictures
rsync $ROPTION --delete --exclude-from=$EXCLUDES/Pictures.exclude /home/cmauch/Pictures /run/media/cmauch/BigWindows/ 

# Videos
rsync $ROPTION --safe-links --exclude 'Recent' --exclude '.porn' --exclude 'Android' --exclude 'Convert' /home/cmauch/Videos /run/media/cmauch/BigWindows/ 

fi

if [ -n "/run/media/cmauch/BigLinux" ]; then

    rsync $ROPTION --delete --safe-links /home/cmauch/Videos/.porn /run/media/cmauch/BigLinux/Videos/
rsync $ROPTION --delete --safe-links /home/cmauch/Videos/Android /run/media/cmauch/BigLinux/Videos/
rsync $ROPTION --delete --safe-links /home/cmauch/Videos/Convert /run/media/cmauch/BigLinux/Videos/

fi

# Notes:
# Add Notify Events to sucessfull / failure to complete script


