#!/bin/sh -e
# $Id$

# -- AUTHOR & COPYRIGHT -------
# Cron Speaker
# Copyright 2011 Charles Mauch (cmauch@gmail.com)
# Licensed under the GPLv3

# -- DESCRIPTION --------------
# Run by cron, Simply speaks the time at the hour or half-hour
# otherwise, speaks out whatever text is fed to it.
#

. /home/cmauch/.Xdbus

if [ "$*" = "hour" ]; then
        # On the Hour 
	echo "Its" `date "+%l oh clock"` | festival --tts
elif [ "$*" = "half" ]; then
	# On the Half Hour
	echo "Its half past " `date "+%l oh clock"` | festival --tts
else
        echo "$*" | festival --tts
fi

