#!/bin/sh
killall avant-window-navigator
avant-window-navigator --startup &

sleep 30

/usr/lib/battery-status/battery-status --indicator &

cd ~/.conky/ConkyGold
~/.conky/ConkyGold/conky.sh

#conky -c .conky/conkylogo -d
#conky -c .conky/date -d

