#!/bin/sh -e

# You can invoke a custom action through this script when fwlogwatch
# issues an alert. A few commented examples are shown below.
# The available arguments (if activated in the configuration, if not the
# fields will contain a '-') are:
# $1 count
# $2 source IP
# $3 destination IP
# $4 protocol
# $5 source port
# $6 destination port

. /etc/default/fwlogwatch
. /home/cmauch/.Xdbus

case "$6" in
  17500)
    sudo -E -u cmauch notify-send --urgency=critical --expire-time=5000 "Firewall Traffic Report" "$2 attempted to connect to Dropbox Service\n... adding to host to AUTORESPOND"
  ;;
  6646)
    sudo -E -u cmauch notify-send --urgency=critical --expire-time=5000 "Firewall Traffic Report" "$2 attempted to connect to McAfee Remote Agent\n... adding to host to AUTORESPOND"
  ;;
  626)
    sudo -E -u cmauch notify-send --urgency=critical --expire-time=5000 "Firewall Traffic Report" "$2 attempted to connect to AppleShare\n... adding to host to AUTORESPOND"
  ;;
  *)
    sudo -E -u cmauch notify-send --urgency=critical --expire-time=5000 "Firewall Traffic Report" "$2 attempted to connect to port $6\n... adding to host to AUTORESPOND"
  ;;
  esac
