#!/bin/bash
# $Id$

# -- AUTHOR & COPYRIGHT -------
# podcast grabber, splitter, etc
# Copyright 2011 Charles Mauch (cmauch@gmail.com)
# Licensed under the GPLv3

# -- DESCRIPTION --------------
# Run by cron, tests for a network connections and if available
# runs podracer and tries to split up large podcasts into segments
# based on mp3 sync errors (which usually indicates an appended
# mp3 file).  m3a's are just placed into the Podcast directory.

# -- RELATED ------------------
# see color-temp.sh and redshift man page
#

WORKDONE=0
TEMPDIR="/home/cmauch/temp/rawpodcasts"
DESTDIR="/home/cmauch/Music/Collections/Podcasts"

if [ `nm-tool|grep State|cut -f2 -d' '` == "connected" ]; then

 if [ ! -f $TEMPDIR ]; then
  echo "Creating temp mp3 download directory ..."
  mkdir -p $TEMPDIR
 fi

	# Run podracer to download any new podcasts
	/usr/bin/podracer
    echo "Podcasts downloaded..."
	
    # Handle m4a files first (move em)
    for i in $TEMPDIR/*.m4a
	 do
	  mv $i $DESTDIR/ &> /dev/null
	  if [ -f $DESTDIR/$i ]; then
           echo "Moving $i to Podcast Directory..."
           ~/bin/send-podcast-notice "$i"
          WORKDONE=1
          fi
	done

	# Now split the podcasts into segments
	for i in $TEMPDIR/*.mp3
	 do
	  nicename=`basename $i .mp3`
      echo "Splitting $nicename-@n ..."
	  mp3splt -eqd $DESTDIR -o $nicename-@n $i &> /dev/null
	  if [ -f $DESTDIR/$nicename-@n ]; then
           ~/bin/send-podcast-notice "$nicename-@n"
           WORKDONE=1
          fi
	done

fi

if [ $WORKDONE = 1 ]; then
 ~/bin/send-podcast-notice "Finished Downloading Podcasts"
fi
