#!/usr/bin/bash


# get current power usage
display_power() {
    if [[ "$(find /sys/class/power_supply -name BAT*)" == "" ]]; then
        echo "[powerdown] no battery"
        return
    fi
    for bat in /sys/class/power_supply/BAT*; do
        local watt
        if [[ -f "$bat/power_now" ]]; then
            watt="$(echo "scale=3; $(cat "$bat"/power_now) / 1000000" | bc)"
        else
            watt="$(echo "scale=3; $(cat "$bat"/current_now) / 1000000" | bc)"
        fi
        echo "[powerdown] $(basename "$bat") using $watt watts"
    done
}


display_power
