#!/bin/sh
# $Id$

# -- AUTHOR & COPYRIGHT -------
# Xsession post-startup script
# Copyright 2011 Charles Mauch (cmauch@gmail.com)
# Licensed under the GPLv3

# -- DESCRIPTION --------------
# Run after most of gnome is up and running, ensures
# conky is started after a proper delay

# Let things settle down
sleep 30

# Fire up conky, which is called by another script
cd ~/.conky/ConkyGold
~/.conky/ConkyGold/conky.sh

sleep 30
killall gnome-screensaver
