#!/bin/sh
# $Id$

# -- AUTHOR & COPYRIGHT -------
# Xsession post-startup script
# Copyright 2011 Charles Mauch (cmauch@gmail.com)
# Licensed under the GPLv3

# -- DESCRIPTION --------------
# Run after most of gnome is up and running

unclutter -noevents -jitter 3 -idle 2 &

sleep 120
killall gwibber-service


# Let things settle down
#sleep 60

# Fire up conky, which is called by another script
#cd ~/.conky/ConkyGold
#~/.conky/ConkyGold/conky.sh
