#!/usr/bin/perl

my $open = 0;
my $closed = 0;

&FindAPs();

## find access points
sub FindAPs {
    my $apoints = `/sbin/iwlist eth1 scanning`;
    my @spoints = split /Cell/, $apoints;

    my $j=0;
    undef(@Address);
    undef(@ESSID);
    undef(@Mode);
    undef(@Frequency);
    undef(@Encryption);
    undef(@Quality);
    undef(@Signal);
    undef(@Noise);
    undef(@Speed);

    ## parse found APs
    for (my $i=0; $i<=$#spoints; $i++) {

        if ($spoints[$i] =~/Address:\s*(\w\w:\w\w:\w\w:\w\w:\w\w:\w\w)/i) {
            $j++;
            $Address[$j] = $1;

            if ($spoints[$i] =~/ESSID:\s*\"(.*)\"/i) {
                $ESSID[$j] = $1;
            }
            if ($spoints[$i] =~/Mode:\s*(Managed|Ad\-hoc|Auto|Master)\s*/i) {
                $Mode[$j] = $1;
            }
            if ($spoints[$i] =~/Frequency:\s*([\w\.]+)\s*/i) {
                $Frequency[$j] = $1;
            }
            if ($spoints[$i] =~/Encryption key:\s*(on|off)\s*/i) {
                $Encryption[$j] = $1;
            }
            if ($spoints[$i] =~/Quality:(.*?)\s/i) {
                $Quality[$j] = $1;
            }
            if ($spoints[$i] =~/Signal level:(.*?)\sdBm/i) {
                $Signal[$j] = $1;
            }
            if ($spoints[$i] =~/Noise level:(.*?)\s*dBm/i) {
                $Noise[$j] = $1;
            }
            if ($spoints[$i] =~/(11)\ Mb\/s/i) {
                $Speed[$j] = "802.11b";
            }
            if ($spoints[$i] =~/(54)\ Mb\/s/i) {
                $Speed[$j] = "802.11ag";
            }
        }
    }

    ## show found APs
    &ListOpenAPs;
    if ( $open != 0 ) {
      print "$count WiFi Open"
    } else {
      print "No WiFi"
    }
}


## list APs
sub ListOpenAPs {
    for (my $j=1; $j<=$#Address; $j++) {
	next if ( $Encryption[$j] eq "on" );
        $open++;
    }
}
