#!/bin/bash
# Script name: /lib/systemd/system-sleep/rtc-hibernate
# Purpose: Auto hibernates after a period of sleep
# Edit the "autohibernate" variable below to set the number of seconds to sleep.

curtime=$(date +%s)

# 60 Minutes should be fine
autohibernate=3600

echo "$curtime $1" >>/tmp/autohibernate.log


if [ "$1" = "pre" ]
then
	if [ "$2" = "suspend" ]
	then
    		# Suspending.  Record current time, and set a wake up timer.
    		echo "$curtime" >/var/run/systemd/rtchibernate.lock
    		rtcwake -m no -s $autohibernate
	fi
fi

if [ "$1" = "post" ]
then

	if [ "$2" = "suspend" ]
	then
    		# Coming out of sleep
    		sustime=$(cat /var/run/systemd/rtchibernate.lock)
    		rm /var/run/systemd/rtchibernate.lock

    		# Did we wake up due to the rtc timer above?
    		if [ $(($curtime - $sustime)) -ge $autohibernate ]
    		then
        		# Then hibernate
        		/usr/bin/systemctl hibernate
    		else
       			# Otherwise cancel the rtc timer and wake up normally.
        		rtcwake -m no -s 1
		fi
    	fi
fi
